from django.urls import path
from core import views

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "upload/<int:book_id>/",
        views.upload_image,
        name="upload_image",
    ),
    path(
        "book/create/",
        views.book_create,
        name="book_create",
    ),
    path(
        "book/<int:book_id>/",
        views.book_detail,
        name="book_detail",
    ),
    path(
        "image/<int:image_id>/",
        views.show_uploaded_image,
        name="show_uploaded_image",
    ),
    path(
        "image/<int:image_id>/simple_convert/",
        views.simple_convert,
        name="simple_convert",
    ),
    path(
        "image/<int:image_id>/generate_by_ai/",
        views.generate_by_ai,
        name="generate_by_ai",
    ),
    path(
        "route/webhook/",
        views.webhook,
        name="webhook",
    ),
    # URLs do Mercado Pago
    path(
        "payment/create/",
        views.create_payment_preference,
        name="create_payment_preference",
    ),
    path(
        "webhook/mercadopago/",
        views.mercado_pago_webhook,
        name="mercado_pago_webhook",
    ),
    path(
        "payment/success/",
        views.payment_success,
        name="payment_success",
    ),
    path(
        "payment/failure/",
        views.payment_failure,
        name="payment_failure",
    ),
    path(
        "payment/pending/",
        views.payment_pending,
        name="payment_pending",
    ),
    path(
        "payment/status/<str:payment_id>/",
        views.check_payment_status,
        name="check_payment_status",
    ),
    path(
        "payment/methods/",
        views.get_available_payment_methods,
        name="get_payment_methods",
    ),
    path(
        "buy-credits/",
        views.buy_credits,
        name="buy_credits",
    ),
]
